### PR TITLE
Fix dockerfile version not static

### PR DESCRIPTION
**Pull request by KwikKill**
Fix image used by dockerfile using latest.

### CODE REVIEW

**Review by Lugrim — COMMENTED** [review]
I really don't like hardcoding a version, in 3 years no one will think about bumping it and the website will be stuck with an old version, then someone will try to bump 5 versions in a row, it will break, and the website will be abandoned

**Comment by KwikKill** [comment]
> I really don't like hardcoding a version, in 3 years no one will think about bumping it and the website will be stuck with an old version, then someone will try to bump 5 versions in a row, it will break, and the website will be abandoned

I agree with that but I rather be stuck in a stable version than having the same problem as we got in the frontend. We had an internal node error that was caused by a new alpine build.

**Comment by TheBloodMan49** [comment]
> I really don't like hardcoding a version, in 3 years no one will think about bumping it and the website will be stuck with an old version, then someone will try to bump 5 versions in a row, it will break, and the website will be abandoned

I mean we already have all the python package versions frozen so I think we should go that route.
You raise a good point tho, we should make it clear in the documentation that efforts must be made regularly towards updating the infrastructure.

**Comment by TheBloodMan49** [comment]
Currently the dev environment doesn't build because of a breaking change introduced by alpine, so I'm okay with this fix.

**Review by TheBloodMan49 — APPROVED** [review]

**Review by Lugrim — APPROVED** [review]
Alright, for prod, it makes sense

**Comment by Lymkwi** [comment]
> > I really don't like hardcoding a version, in 3 years no one will think about bumping it and the website will be stuck with an old version, then someone will try to bump 5 versions in a row, it will break, and the website will be abandoned
> 
> I agree with that but I rather be stuck in a stable version than having the same problem as we got in the frontend. We had an internal node error that was caused by a new alpine build.

In general, unless you are using cutting edge features, Python is less likely to break on you. They did that once when crossing the threshold from 2 to 3, and people still haven't fully recovered from it.

**Pull request merged**
